"""
Django settings for finalecommerce project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

"""
Django settings for finalecommerce project.
"""

import os
from pathlib import Path


import dj_database_url
# =====================================================

# BASE DIRECTORY

# =====================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# =====================================================

# SECURITY SETTINGS

# =====================================================

SECRET_KEY = os.environ.get(
"DJANGO_SECRET_KEY",
"django-insecure-local-shopkart-development-key-change-this"
)

DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# =====================================================

# ALLOWED HOSTS

# =====================================================

ALLOWED_HOSTS = [
"localhost",
"127.0.0.1",
]
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# =====================================================
# CSRF TRUSTED ORIGINS
# =====================================================

CSRF_TRUSTED_ORIGINS = [
    "https://shopkart-ecommerce-django.onrender.com",
]

if RENDER_EXTERNAL_HOSTNAME:
    render_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"

    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)

# =====================================================
# APPLICATION DEFINITION
# =====================================================

# =====================================================

# APPLICATION DEFINITION

# =====================================================

INSTALLED_APPS = [
"django.contrib.admin",
"django.contrib.auth",
"django.contrib.contenttypes",
"django.contrib.sessions",
"django.contrib.messages",
"django.contrib.staticfiles",
"appaccount",
]

# =====================================================

# MIDDLEWARE

# =====================================================

MIDDLEWARE = [
"django.middleware.security.SecurityMiddleware",
"whitenoise.middleware.WhiteNoiseMiddleware",
"django.contrib.sessions.middleware.SessionMiddleware",
"django.middleware.common.CommonMiddleware",
"django.middleware.csrf.CsrfViewMiddleware",
"django.contrib.auth.middleware.AuthenticationMiddleware",
"django.contrib.messages.middleware.MessageMiddleware",
"django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# =====================================================

# URL CONFIGURATION

# =====================================================

ROOT_URLCONF = "finalecommerce.urls"

# =====================================================

# TEMPLATES

# =====================================================

TEMPLATES = [
{
"BACKEND": "django.template.backends.django.DjangoTemplates",
"DIRS": [BASE_DIR / "templates"],
"APP_DIRS": True,
"OPTIONS": {
"context_processors": [
"django.template.context_processors.request",
"django.contrib.auth.context_processors.auth",
"django.contrib.messages.context_processors.messages",
],
},
},
]

WSGI_APPLICATION = "finalecommerce.wsgi.application"

# =====================================================

# DATABASE

# Render: PostgreSQL

# Local computer: SQLite

# =====================================================

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
 DATABASES = {
"default": dj_database_url.parse(
DATABASE_URL,
conn_max_age=600,
ssl_require=True,
)
}
else:
 DATABASES = {
"default": {
"ENGINE": "django.db.backends.sqlite3",
"NAME": BASE_DIR / "db.sqlite3",
}
}

# =====================================================

# PASSWORD VALIDATION

# =====================================================

AUTH_PASSWORD_VALIDATORS = [
{
"NAME": (
"django.contrib.auth.password_validation."
"UserAttributeSimilarityValidator"
),
},
{
"NAME": (
"django.contrib.auth.password_validation."
"MinimumLengthValidator"
),
},
{
"NAME": (
"django.contrib.auth.password_validation."
"CommonPasswordValidator"
),
},
{
"NAME": (
"django.contrib.auth.password_validation."
"NumericPasswordValidator"
),
},
]

# =====================================================

# INTERNATIONALIZATION

# =====================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True
USE_TZ = True

# =====================================================

# STATIC FILES

# =====================================================
STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "media",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
# MEDIA FILES

# =====================================================



MEDIA_ROOT = BASE_DIR / "media"

# =====================================================

# EMAIL SETTINGS

# =====================================================

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# =====================================================

# LOGGING

# =====================================================

LOGGING = {
"version": 1,
"disable_existing_loggers": False,
"handlers": {
"console": {
"class": "logging.StreamHandler",
},
},
"loggers": {
"django.request": {
"handlers": ["console"],
"level": "ERROR",
"propagate": False,
},
},
}

# =====================================================

# DEFAULT PRIMARY KEY

# =====================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
